INSERT INTO OBJTYPE (OBJECT_TYPE_ID,PARENT_ID,CODE,NAME,DESCRIPTION) values(1,NULL,'USER','ÏÎËÜÇÎÂÀÒÅËÜ',NULL);

INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) values(1,1,NULL,'EMAIL','ÏÎ×ÒÎÂÛÉ ÀÄÐÅÑ');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) values(2,1,NULL,'PASSWORD','ÏÀÐÎËÜ');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) values(3,1,NULL,'NAME','ÈÌß');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) values(4,1,NULL,'SURNAME','ÔÀÌÈËÈß');

CREATE SEQUENCE object_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE attribute_sequence START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE createUser(
email in varchar2,
pass in varchar2,
username in varchar2,
surname in varchar2
)
IS
BEGIN
  INSERT INTO OBJECTS(OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) values (object_sequence.nextval,NULL,1,email,NULL);
  INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) values(1,object_sequence.currval,email,null);
  INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) values(2,object_sequence.currval,pass,null);
  INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) values(3,object_sequence.currval,username,null);
  INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) values(4,object_sequence.currval,surname,null);
END;

EXECUTE CREATEUSER('oda21101@mail.ru','12345','Bogdan','Hadzhiev');

CREATE OR REPLACE FUNCTION isExistUser(
email in varchar2
)RETURN varchar2
IS
user_count number;
BEGIN
  SELECT count(USR.NAME) INTO user_count
  FROM OBJECTS USR, OBJTYPE USR_TYPE 
  WHERE USR.NAME = email
        AND USR_TYPE.CODE = 'USER'
      	AND USR_TYPE.OBJECT_TYPE_ID = USR.OBJECT_TYPE_ID;
  IF user_count>0 THEN
    RETURN 'TRUE';
  END IF;
  RETURN 'FALSE';
END;